# Generated by Django 4.2.3 on 2023-07-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('picture', models.ImageField(height_field=400, null=True, upload_to=None, width_field=400)),
                ('mood', models.IntegerField(choices=[(5, '❤️❤️❤️❤️❤️'), (2, '💙💙'), (3, '💚💚💚'), (1, '💜'), (4, '💛💛💛💛')])),
            ],
        ),
    ]
