# Generated by Django 4.2.3 on 2023-07-25 06:36

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('painting', django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True)),
                ('mood', models.IntegerField(choices=[(2, '💙💙'), (4, '💛💛💛💛'), (1, '💜'), (3, '💚💚💚'), (5, '❤️❤️❤️❤️❤️')])),
            ],
        ),
    ]
