# Generated by Django 4.2.3 on 2023-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.IntegerField(choices=[(4, '💛💛💛💛'), (1, '💜'), (2, '💙💙'), (3, '💚💚💚'), (5, '❤️❤️❤️❤️❤️')]),
        ),
    ]
