# Generated by Django 4.2.3 on 2023-07-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.IntegerField(choices=[(1, '💜'), (4, '💛💛💛💛'), (2, '💙💙'), (5, '❤️❤️❤️❤️❤️'), (3, '💚💚💚')]),
        ),
    ]
